version: '2'
services:
  java:
    build:
      context: ./java8
      dockerfile: java8.dockerfile
    image: registry.docker.kosmala.work/jdk:java8
  hadoop-base:
    build:
      context: ./hadoop-base
      dockerfile: hadoop-base.dockerfile
    image: registry.docker.kosmala.work/hadoop/hadoop-base:base

