version: '2'
services:
  java:
    build:
      context: ./java8
      dockerfile: java8.dockerfile
    image: registry.docker.kosmala.work/jdk:java8
  hadoop-base:
    build:
      context: ./hadoop-base
      dockerfile: Dockerfile
    image: registry.docker.kosmala.work/hadoop/hadoop-base
  hadoop-datanode:
    build:
      context: ./hadoop-datanode
      dockerfile: Dockerfile
    image: registry.docker.kosmala.work/hadoop/hadoop-datanode
  hadoop-history:
    build:
      context: ./hadoop-history
      dockerfile: Dockerfile
    image: registry.docker.kosmala.work/hadoop/hadoop-history
  hadoop-mapreduce:
    build:
      context: ./hadoop-mapreduce
      dockerfile: Dockerfile
    image: registry.docker.kosmala.work/hadoop/hadoop-mapreduce
  hadoop-mapreduce-jobhistory:
    build:
      context: ./hadoop-mapreduce-jobhistory
      dockerfile: Dockerfile
    image: registry.docker.kosmala.work/hadoop/hadoop-mapreduce-jobhistory
  hadoop-namenode:
    build:
      context: ./hadoop-namenode
      dockerfile: Dockerfile
    image: registry.docker.kosmala.work/hadoop/hadoop-namenode
  hadoop-nodemanager:
    build:
      context: ./hadoop-nodemanager
      dockerfile: Dockerfile
    image: registry.docker.kosmala.work/hadoop/hadoop-nodemanager
    depends_on:
      - hadoop-base
      - hadoop-resourcemanager
    links:
      - hadoop-resourcemanager
  hadoop-resourcemanager:
    build:
      context: ./hadoop-resourcemanager
      dockerfile: Dockerfile
    image: registry.docker.kosmala.work/hadoop/hadoop-resourcemanager
